import { ChatMessage, LeaderboardEntry, Problem, Profile, Streak } from '../types';
import { format, subDays, subMinutes, subHours } from 'date-fns';

const today = new Date();

export const INITIAL_MOCK_PROFILE: Profile = {
  id: 'mock-user-123',
  full_name: 'Vishwa Patel',
  username: 'vishwa_codes',
  email: 'vishwa.patel@example.com',
  college: 'National Institute of Technology',
  branch: 'Computer Science & Engineering',
  graduation_year: 2026,
  bio: 'Consistent problem solver practicing DSA and system design for software engineering placements. 💻📚',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  target_goal: 500,
  role: 'user',
  status: 'active',
  created_at: subDays(today, 120).toISOString(),
};

export const INITIAL_MOCK_STREAK: Streak = {
  user_id: 'mock-user-123',
  current_streak: 14,
  longest_streak: 28,
  last_active_date: format(today, 'yyyy-MM-dd'),
};

export const INITIAL_MOCK_PROBLEMS: Problem[] = [
  {
    id: 'prob-1',
    user_id: 'mock-user-123',
    problem_id: 'LC-1',
    problem_name: 'Two Sum',
    platform: 'LeetCode',
    difficulty: 'Easy',
    topic: 'Arrays',
    problem_link: 'https://leetcode.com/problems/two-sum/',
    notes: '### Approach & Intuition\nUse a **Hash Map** (`unordered_map` in C++ / `dict` in Python) to store values and their indices. For each element `num`, check if `target - num` exists.\n\n```cpp\nunordered_map<int, int> seen;\nfor (int i = 0; i < nums.size(); ++i) {\n    int comp = target - nums[i];\n    if (seen.count(comp)) return {seen[comp], i};\n    seen[nums[i]] = i;\n}\n```\n- **Time Complexity**: $O(N)$\n- **Space Complexity**: $O(N)$',
    solved_date: format(subDays(today, 0), 'yyyy-MM-dd'),
    time_taken: 12,
    favorite: true,
    revision_needed: false,
    revision_count: 1,
    last_revised_at: format(subDays(today, 2), 'yyyy-MM-dd'),
    created_at: subDays(today, 0).toISOString(),
  },
  {
    id: 'prob-2',
    user_id: 'mock-user-123',
    problem_id: 'LC-3',
    problem_name: 'Longest Substring Without Repeating Characters',
    platform: 'LeetCode',
    difficulty: 'Medium',
    topic: 'Sliding Window',
    problem_link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    notes: '### Sliding Window Technique\nMaintain variable window `[left, right]`. Use a hash map of `char -> last_seen_index`. When duplicate is detected, jump `left = max(left, last_seen[char] + 1)`.\n\n- Key edge case: Ensure `left` only moves forward.',
    solved_date: format(subDays(today, 1), 'yyyy-MM-dd'),
    time_taken: 25,
    favorite: true,
    revision_needed: true,
    revision_date: format(today, 'yyyy-MM-dd'),
    revision_count: 2,
    last_revised_at: format(subDays(today, 4), 'yyyy-MM-dd'),
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'prob-3',
    user_id: 'mock-user-123',
    problem_id: 'LC-42',
    problem_name: 'Trapping Rain Water',
    platform: 'LeetCode',
    difficulty: 'Hard',
    topic: 'Two Pointers',
    problem_link: 'https://leetcode.com/problems/trapping-rain-water/',
    notes: '### Optimal Two Pointers\nTrack `left_max` and `right_max`. Water trapped at `left` depends on `left_max <= right_max`. Move smaller pointer inward.\n\n- **Time**: $O(N)$\n- **Space**: $O(1)$',
    solved_date: format(subDays(today, 2), 'yyyy-MM-dd'),
    time_taken: 45,
    favorite: true,
    revision_needed: true,
    revision_date: format(today, 'yyyy-MM-dd'),
    revision_count: 0,
    created_at: subDays(today, 2).toISOString(),
  },
  {
    id: 'prob-4',
    user_id: 'mock-user-123',
    problem_id: 'LC-206',
    problem_name: 'Reverse Linked List',
    platform: 'LeetCode',
    difficulty: 'Easy',
    topic: 'Linked List',
    problem_link: 'https://leetcode.com/problems/reverse-linked-list/',
    notes: 'Classic 3 pointers: `prev = null`, `curr = head`, `next = curr.next`. Reconnect pointers step by step.',
    solved_date: format(subDays(today, 3), 'yyyy-MM-dd'),
    time_taken: 10,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 3).toISOString(),
  },
  {
    id: 'prob-5',
    user_id: 'mock-user-123',
    problem_id: 'GFG-4',
    problem_name: "Kadane's Algorithm",
    platform: 'GFG',
    difficulty: 'Medium',
    topic: 'Dynamic Programming',
    problem_link: 'https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1',
    notes: '`curr_sum = Math.max(x, curr_sum + x); max_sum = Math.max(max_sum, curr_sum);`',
    solved_date: format(subDays(today, 4), 'yyyy-MM-dd'),
    time_taken: 15,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 4).toISOString(),
  },
  {
    id: 'prob-6',
    user_id: 'mock-user-123',
    problem_id: 'CF-158A',
    problem_name: 'Next Round',
    platform: 'Codeforces',
    difficulty: 'Easy',
    topic: 'Arrays',
    problem_link: 'https://codeforces.com/problemset/problem/158/A',
    notes: 'Direct iteration checking score >= k-th participant score and positive.',
    solved_date: format(subDays(today, 5), 'yyyy-MM-dd'),
    time_taken: 8,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 5).toISOString(),
  },
  {
    id: 'prob-7',
    user_id: 'mock-user-123',
    problem_id: 'LC-200',
    problem_name: 'Number of Islands',
    platform: 'LeetCode',
    difficulty: 'Medium',
    topic: 'Graphs',
    problem_link: 'https://leetcode.com/problems/number-of-islands/',
    notes: '### Grid DFS / BFS\nTraverse grid. When `grid[r][c] == "1"`, increment count and trigger DFS to sink all connected land to `"0"`.',
    solved_date: format(subDays(today, 6), 'yyyy-MM-dd'),
    time_taken: 20,
    favorite: true,
    revision_needed: false,
    created_at: subDays(today, 6).toISOString(),
  },
  {
    id: 'prob-8',
    user_id: 'mock-user-123',
    problem_id: 'LC-70',
    problem_name: 'Climbing Stairs',
    platform: 'LeetCode',
    difficulty: 'Easy',
    topic: 'Dynamic Programming',
    problem_link: 'https://leetcode.com/problems/climbing-stairs/',
    notes: 'Equivalent to Fibonacci numbers. `dp[i] = dp[i-1] + dp[i-2]`. Space can be optimized to $O(1)$.',
    solved_date: format(subDays(today, 7), 'yyyy-MM-dd'),
    time_taken: 5,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 7).toISOString(),
  },
  {
    id: 'prob-9',
    user_id: 'mock-user-123',
    problem_id: 'LC-23',
    problem_name: 'Merge k Sorted Lists',
    platform: 'LeetCode',
    difficulty: 'Hard',
    topic: 'Heap / Priority Queue',
    problem_link: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    notes: '### Min Heap Solution\nInsert head of each list into Min Heap. Extract min, add to result list, and push next node into heap.\n- **Time**: $O(N \\log K)$ where $K$ is number of lists.',
    solved_date: format(subDays(today, 8), 'yyyy-MM-dd'),
    time_taken: 35,
    favorite: true,
    revision_needed: true,
    revision_date: format(subDays(today, -1), 'yyyy-MM-dd'),
    revision_count: 1,
    created_at: subDays(today, 8).toISOString(),
  },
  {
    id: 'prob-10',
    user_id: 'mock-user-123',
    problem_id: 'HR-ARRAY',
    problem_name: 'Dynamic Array',
    platform: 'HackerRank',
    difficulty: 'Easy',
    topic: 'Arrays',
    problem_link: 'https://www.hackerrank.com/challenges/dynamic-array/problem',
    notes: '2D dynamic list querying logic using XOR bitwise operations.',
    solved_date: format(subDays(today, 9), 'yyyy-MM-dd'),
    time_taken: 15,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 9).toISOString(),
  },
  {
    id: 'prob-11',
    user_id: 'mock-user-123',
    problem_id: 'LC-121',
    problem_name: 'Best Time to Buy and Sell Stock',
    platform: 'LeetCode',
    difficulty: 'Easy',
    topic: 'Arrays',
    problem_link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    notes: 'Single pass: keep minimum price so far and calculate `max_profit = max(max_profit, price - min_price)`.',
    solved_date: format(subDays(today, 10), 'yyyy-MM-dd'),
    time_taken: 7,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 10).toISOString(),
  },
  {
    id: 'prob-12',
    user_id: 'mock-user-123',
    problem_id: 'LC-300',
    problem_name: 'Longest Increasing Subsequence',
    platform: 'LeetCode',
    difficulty: 'Medium',
    topic: 'Dynamic Programming',
    problem_link: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    notes: '### Binary Search $O(N \\log N)$ Patience Sorting\nMaintain `tails` array. For each number, binary search for insertion position.',
    solved_date: format(subDays(today, 11), 'yyyy-MM-dd'),
    time_taken: 30,
    favorite: true,
    revision_needed: true,
    revision_date: format(subDays(today, -5), 'yyyy-MM-dd'),
    revision_count: 0,
    created_at: subDays(today, 11).toISOString(),
  },
  {
    id: 'prob-13',
    user_id: 'mock-user-123',
    problem_id: 'CC-FLOW001',
    problem_name: 'Add Two Numbers',
    platform: 'CodeChef',
    difficulty: 'Easy',
    topic: 'Math & Geometry',
    problem_link: 'https://www.codechef.com/problems/FLOW001',
    notes: 'Fast I/O basic practice.',
    solved_date: format(subDays(today, 12), 'yyyy-MM-dd'),
    time_taken: 3,
    favorite: false,
    revision_needed: false,
    created_at: subDays(today, 12).toISOString(),
  },
  {
    id: 'prob-14',
    user_id: 'mock-user-123',
    problem_id: 'LC-146',
    problem_name: 'LRU Cache',
    platform: 'LeetCode',
    difficulty: 'Medium',
    topic: 'System Design',
    problem_link: 'https://leetcode.com/problems/lru-cache/',
    notes: '### Doubly Linked List + Hash Map\nHash map stores key to node pointer. Doubly Linked List allows $O(1)$ remove and append to head.',
    solved_date: format(subDays(today, 13), 'yyyy-MM-dd'),
    time_taken: 35,
    favorite: true,
    revision_needed: false,
    created_at: subDays(today, 13).toISOString(),
  },
  {
    id: 'prob-15',
    user_id: 'mock-user-123',
    problem_id: 'LC-76',
    problem_name: 'Minimum Window Substring',
    platform: 'LeetCode',
    difficulty: 'Hard',
    topic: 'Sliding Window',
    problem_link: 'https://leetcode.com/problems/minimum-window-substring/',
    notes: 'Count map of required characters. Expand right until valid, contract left while maintaining valid condition.',
    solved_date: format(subDays(today, 14), 'yyyy-MM-dd'),
    time_taken: 50,
    favorite: true,
    revision_needed: true,
    revision_date: format(subDays(today, -4), 'yyyy-MM-dd'),
    revision_count: 1,
    created_at: subDays(today, 14).toISOString(),
  }
];

export const INITIAL_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  'room-leetcode-daily': [
    {
      id: 'msg-1',
      room_id: 'room-leetcode-daily',
      user_id: 'user-001',
      username: 'priyacodes',
      full_name: 'Priya Sharma',
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      content: '📌 **Daily Strategy Tip**: For today’s LeetCode challenge, notice how sorting the array allows a clean two-pointer contraction in $O(N \\log N)$. Avoid brute-forcing three nested loops!',
      created_at: subHours(today, 2).toISOString(),
      is_pinned: true,
      reactions: { '🔥': ['user-002', 'user-003'], '👏': ['user-001', 'mock-user-123'] },
    },
    {
      id: 'msg-2',
      room_id: 'room-leetcode-daily',
      user_id: 'user-002',
      username: 'rohan_dev',
      full_name: 'Rohan Gupta',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      content: 'Agreed! Also watch out for duplicate triplets. Remember to increment left and decrement right while skipping adjacent equal values.',
      created_at: subMinutes(today, 45).toISOString(),
      reactions: { '💡': ['mock-user-123'] },
    },
    {
      id: 'msg-3',
      room_id: 'room-leetcode-daily',
      user_id: 'mock-user-123',
      username: 'vishwa_codes',
      full_name: 'Vishwa Patel',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      content: 'Just solved it in 18 minutes! Here is the clean C++ condition:\n```cpp\nwhile (left < right && nums[left] == nums[left+1]) left++;\nwhile (left < right && nums[right] == nums[right-1]) right--;\n```',
      created_at: subMinutes(today, 10).toISOString(),
      shared_problem: {
        problem_id: 'LC-15',
        problem_name: '3Sum',
        platform: 'LeetCode',
        difficulty: 'Medium',
        link: 'https://leetcode.com/problems/3sum/',
      },
      reactions: { '🚀': ['user-001', 'user-002'] },
    },
  ],
  'room-dp-mastery': [
    {
      id: 'msg-dp-1',
      room_id: 'room-dp-mastery',
      user_id: 'user-003',
      username: 'siddharth_algo',
      full_name: 'Siddharth Sen',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      content: 'Pinned summary for 0/1 Knapsack vs Unbounded Knapsack: When an item can be picked multiple times, the inner loop runs forward rather than backward.',
      created_at: subHours(today, 5).toISOString(),
      is_pinned: true,
    },
  ],
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    id: 'user-001',
    full_name: 'Priya Sharma',
    username: 'priyacodes',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    total_solved: 642,
    easy_count: 180,
    medium_count: 360,
    hard_count: 102,
    current_streak: 114,
    longest_streak: 114,
    is_friend: true,
    weekly_solved: 18,
    monthly_solved: 72,
  },
  {
    rank: 2,
    id: 'user-002',
    full_name: 'Rohan Gupta',
    username: 'rohan_dev',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    total_solved: 580,
    easy_count: 150,
    medium_count: 330,
    hard_count: 100,
    current_streak: 89,
    longest_streak: 95,
    is_friend: false,
    weekly_solved: 14,
    monthly_solved: 60,
  },
  {
    rank: 3,
    id: 'user-003',
    full_name: 'Siddharth Sen',
    username: 'siddharth_algo',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    total_solved: 512,
    easy_count: 140,
    medium_count: 290,
    hard_count: 82,
    current_streak: 62,
    longest_streak: 75,
    is_friend: true,
    weekly_solved: 11,
    monthly_solved: 48,
  },
  {
    rank: 4,
    id: 'mock-user-123',
    full_name: 'Vishwa Patel (You)',
    username: 'vishwa_codes',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    total_solved: 348,
    easy_count: 112,
    medium_count: 198,
    hard_count: 38,
    current_streak: 14,
    longest_streak: 28,
    is_friend: false,
    weekly_solved: 9,
    monthly_solved: 38,
  },
  {
    rank: 5,
    id: 'user-004',
    full_name: 'Ananya Verma',
    username: 'ananya_v',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    total_solved: 310,
    easy_count: 95,
    medium_count: 175,
    hard_count: 40,
    current_streak: 21,
    longest_streak: 45,
    is_friend: false,
    weekly_solved: 8,
    monthly_solved: 34,
  },
  {
    rank: 6,
    id: 'user-005',
    full_name: 'Kavya Nair',
    username: 'kavya_codes',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    total_solved: 275,
    easy_count: 90,
    medium_count: 155,
    hard_count: 30,
    current_streak: 18,
    longest_streak: 33,
    is_friend: true,
    weekly_solved: 7,
    monthly_solved: 29,
  },
  {
    rank: 7,
    id: 'user-006',
    full_name: 'Devansh Roy',
    username: 'dev_roy',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    total_solved: 240,
    easy_count: 80,
    medium_count: 135,
    hard_count: 25,
    current_streak: 9,
    longest_streak: 42,
    is_friend: false,
    weekly_solved: 5,
    monthly_solved: 22,
  },
];
